package com.squareup.moshix.sealedswiftcompat

import com.google.common.truth.Truth.assertThat
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import com.tschuchort.compiletesting.configureKsp
import com.tschuchort.compiletesting.kspSourcesDir
import java.io.File
import org.junit.Test

/**
 * Based on
 * [https://github.com/ZacSweers/MoshiX/blob/main/moshi-sealed/codegen/src/test/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorTest.kt].
 */
class MoshiSealedSymbolProcessorProviderTest {
  companion object {
    val DATA_CLASS =
        kotlin(
            "MyClass.kt",
            """
            package com.example

            import com.squareup.moshi.Json
            import com.squareup.moshi.JsonClass

            @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
            data class MyClass(
              val test: String,
              val test2: Int,
              val test3: Boolean,
              val test4: List<String>,
              val test5: EnumOne,
            )
            """
                .trimIndent(),
        )
    val ENUM_CLASSES =
        kotlin(
            "Enums.kt",
            """
            package com.example

            import com.squareup.moshi.Json

            enum class EnumOne {
              One,
              Two
            }

            enum class EnumTwo {
              @Json(name = "1")
              One,
              @Json(name = "2")
              Two
            }
            """
                .trimIndent(),
        )
    val SEALED_INTERFACE =
        kotlin(
            "TestInterface.kt",
            """
            package com.example

            import com.squareup.moshi.Json
            import com.squareup.moshi.JsonClass

            @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
            sealed interface TestInterface {
              @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
              data class TestA(
                val a: Int,
                val b: EnumOne,
                val c: MyClass,
              ) : TestInterface

              @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
              data class TestB(val b: String) : TestInterface

              data object TestC : TestInterface
            }
            """
                .trimIndent(),
        )
    val SEALED_INTERFACE_WITH_NAMES =
        kotlin(
            "TestInterface.kt",
            """
            package com.example

            import com.squareup.moshi.Json
            import com.squareup.moshi.JsonClass

            @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
            sealed interface TestInterface {
              @Json(name = "a")
              @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
              data class TestA(
                val a: Int,
                val b: EnumOne,
                val c: MyClass,
              ) : TestInterface

              @Json(name = "b")
              @JsonClass(generateAdapter = true, generator = "sealed-swift-compat")
              data class TestB(val b: String) : TestInterface

              @Json(name = "c")
              data object TestC : TestInterface
            }
            """
                .trimIndent(),
        )
  }

  @Test
  fun topLevelDataClass() {
    val compilation = prepareCompilation(ENUM_CLASSES, DATA_CLASS)
    val result = compilation.compile()
    assertThat(result.exitCode).isEqualTo(ExitCode.OK)

    val generatedSourcesDir = compilation.kspSourcesDir
    val generatedAdapter = File(generatedSourcesDir, "kotlin/com/example/MyClassJsonAdapter.kt")
    assertThat(generatedAdapter.exists()).isTrue()
    // language=kotlin
    assertThat(generatedAdapter.readText().trim())
        .isEqualTo(
            """
            // Code generated by moshi-sealed-swift-compat. Do not edit.
            package com.example

            import com.squareup.moshi.JsonAdapter
            import com.squareup.moshi.JsonReader
            import com.squareup.moshi.JsonWriter
            import com.squareup.moshi.Moshi
            import com.squareup.moshi.Types
            import com.squareup.moshi.`internal`.Util
            import kotlin.Boolean
            import kotlin.Int
            import kotlin.String
            import kotlin.Suppress
            import kotlin.collections.List

            @Suppress("ClassName", "RedundantVisibilityModifier", "unused", "LocalVariableName")
            public class MyClassJsonAdapter(
              moshi: Moshi,
            ) : JsonAdapter<MyClass>() {
              private val options: JsonReader.Options = JsonReader.Options.of("_0", "_1", "_2", "_3", "_4")

              private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java)

              private val intAdapter: JsonAdapter<Int> = moshi.adapter(Int::class.java)

              private val booleanAdapter: JsonAdapter<Boolean> = moshi.adapter(Boolean::class.java)

              private val listOfStringAdapter: JsonAdapter<List<String>> =
                  moshi.adapter(Types.newParameterizedType(List::class.java, String::class.java))

              private val enumOneAdapter: JsonAdapter<EnumOne> = moshi.adapter(EnumOne::class.java)

              override fun fromJson(reader: JsonReader): MyClass {
                var test: String? = null
                var test2: Int? = null
                var test3: Boolean? = null
                var test4: List<String>? = null
                var test5: EnumOne? = null
                reader.beginObject()
                while (reader.hasNext()) {
                  when (reader.selectName(options)) {
                    0 -> test = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("test", "_0", reader)
                    1 -> test2 = intAdapter.fromJson(reader) ?: throw Util.unexpectedNull("test2", "_1", reader)
                    2 -> test3 = booleanAdapter.fromJson(reader) ?: throw Util.unexpectedNull("test3", "_2", reader)
                    3 -> test4 = listOfStringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("test4", "_3", reader)
                    4 -> test5 = enumOneAdapter.fromJson(reader) ?: throw Util.unexpectedNull("test5", "_4", reader)
                    -1 -> {
                      // Unknown name, skip it.
                      reader.skipName()
                      reader.skipValue()
                    }
                  }
                }
                reader.endObject()
                return MyClass(
                  test = test ?: throw Util.missingProperty("test", "_0", reader),
                  test2 = test2 ?: throw Util.missingProperty("test2", "_1", reader),
                  test3 = test3 ?: throw Util.missingProperty("test3", "_2", reader),
                  test4 = test4 ?: throw Util.missingProperty("test4", "_3", reader),
                  test5 = test5 ?: throw Util.missingProperty("test5", "_4", reader),
                )
              }

              override fun toJson(writer: JsonWriter, value_: MyClass?) {
                if (value_ == null) {
                  throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
                }
                writer.beginObject()
                writer.name("_0")
                stringAdapter.toJson(writer, value_.test)
                writer.name("_1")
                intAdapter.toJson(writer, value_.test2)
                writer.name("_2")
                booleanAdapter.toJson(writer, value_.test3)
                writer.name("_3")
                listOfStringAdapter.toJson(writer, value_.test4)
                writer.name("_4")
                enumOneAdapter.toJson(writer, value_.test5)
                writer.endObject()
              }
            }
            """
                .trimIndent(),
        )
  }

  @Test
  fun sealedInterface() {
    val compilation = prepareCompilation(ENUM_CLASSES, DATA_CLASS, SEALED_INTERFACE)
    val result = compilation.compile()
    assertThat(result.exitCode).isEqualTo(ExitCode.OK)

    val generatedSourcesDir = compilation.kspSourcesDir
    val generatedAdapter =
        File(generatedSourcesDir, "kotlin/com/example/TestInterfaceJsonAdapter.kt")
    assertThat(generatedAdapter.exists()).isTrue()
    // language=kotlin
    assertThat(generatedAdapter.readText().trim())
        .isEqualTo(
            """
            // Code generated by moshi-sealed-swift-compat. Do not edit.
            package com.example

            import com.squareup.moshi.JsonAdapter
            import com.squareup.moshi.JsonReader
            import com.squareup.moshi.JsonWriter
            import com.squareup.moshi.Moshi
            import kotlin.Suppress

            @Suppress("ClassName", "RedundantVisibilityModifier", "unused", "LocalVariableName")
            public class TestInterfaceJsonAdapter(
              moshi: Moshi,
            ) : JsonAdapter<TestInterface>() {
              private val testAAdapter: JsonAdapter<TestInterface.TestA> =
                  moshi.adapter(TestInterface.TestA::class.java)

              private val testBAdapter: JsonAdapter<TestInterface.TestB> =
                  moshi.adapter(TestInterface.TestB::class.java)

              override fun fromJson(reader: JsonReader): TestInterface? {
                reader.beginObject()
                val name = reader.nextName()
                val result = when (name) {
                  "TestA" -> testAAdapter.fromJson(reader)
                  "TestB" -> testBAdapter.fromJson(reader)
                  "TestC" -> {
                    reader.skipValue()
                    TestInterface.TestC
                  }
                  else -> {
                    reader.skipValue()
                    null
                  }
                }
                reader.endObject()
                return result
              }

              override fun toJson(writer: JsonWriter, value_: TestInterface?) {
                if (value_ == null) {
                  throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
                }
                writer.beginObject()
                when (value_) {
                  is TestInterface.TestA -> {
                    writer.name("TestA")
                    testAAdapter.toJson(writer, value_)
                  }
                  is TestInterface.TestB -> {
                    writer.name("TestB")
                    testBAdapter.toJson(writer, value_)
                  }
                  is TestInterface.TestC -> {
                    writer.name("TestC")
                    writer.beginObject()
                    writer.endObject()
                  }
                }
                writer.endObject()
              }
            }
            """
                .trimIndent(),
        )
  }

  @Test
  fun sealedInterfaceWithNames() {
    val compilation =
        prepareCompilation(
            ENUM_CLASSES,
            DATA_CLASS,
            SEALED_INTERFACE_WITH_NAMES,
        )
    val result = compilation.compile()
    assertThat(result.exitCode).isEqualTo(ExitCode.OK)

    val generatedSourcesDir = compilation.kspSourcesDir
    val generatedAdapter =
        File(generatedSourcesDir, "kotlin/com/example/TestInterfaceJsonAdapter.kt")
    assertThat(generatedAdapter.exists()).isTrue()
    // language=kotlin
    assertThat(generatedAdapter.readText().trim())
        .isEqualTo(
            """
            // Code generated by moshi-sealed-swift-compat. Do not edit.
            package com.example

            import com.squareup.moshi.JsonAdapter
            import com.squareup.moshi.JsonReader
            import com.squareup.moshi.JsonWriter
            import com.squareup.moshi.Moshi
            import kotlin.Suppress

            @Suppress("ClassName", "RedundantVisibilityModifier", "unused", "LocalVariableName")
            public class TestInterfaceJsonAdapter(
              moshi: Moshi,
            ) : JsonAdapter<TestInterface>() {
              private val testAAdapter: JsonAdapter<TestInterface.TestA> =
                  moshi.adapter(TestInterface.TestA::class.java)

              private val testBAdapter: JsonAdapter<TestInterface.TestB> =
                  moshi.adapter(TestInterface.TestB::class.java)

              override fun fromJson(reader: JsonReader): TestInterface? {
                reader.beginObject()
                val name = reader.nextName()
                val result = when (name) {
                  "a" -> testAAdapter.fromJson(reader)
                  "b" -> testBAdapter.fromJson(reader)
                  "c" -> {
                    reader.skipValue()
                    TestInterface.TestC
                  }
                  else -> {
                    reader.skipValue()
                    null
                  }
                }
                reader.endObject()
                return result
              }

              override fun toJson(writer: JsonWriter, value_: TestInterface?) {
                if (value_ == null) {
                  throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
                }
                writer.beginObject()
                when (value_) {
                  is TestInterface.TestA -> {
                    writer.name("a")
                    testAAdapter.toJson(writer, value_)
                  }
                  is TestInterface.TestB -> {
                    writer.name("b")
                    testBAdapter.toJson(writer, value_)
                  }
                  is TestInterface.TestC -> {
                    writer.name("c")
                    writer.beginObject()
                    writer.endObject()
                  }
                }
                writer.endObject()
              }
            }
            """
                .trimIndent(),
        )
  }

  private fun prepareCompilation(vararg sourceFiles: SourceFile): KotlinCompilation =
      KotlinCompilation().apply {
        sources = sourceFiles.toList()
        inheritClassPath = true
        configureKsp { symbolProcessorProviders += MoshiSealedSwiftCompatProcessorProvider() }
        kotlincArguments += "-Xskip-prerelease-check"
      }
}
